#!/usr/bin/env bash

LOCAL_USER=starry
SITE_USER=starry
SITE_URL=astrostucky.com
SITE_PATH=/var/www/html/
OUTPUT_DIR=output/

if [ ! -d "content" ]; then
  echo "Content directory missing!";
  exit 1;
fi

# build website locally
pelican content -s publishconf.py

if [ ! -d "$OUTPUT_DIR" ]; then
  echo "Pelican output directory missing!";
  exit 1;
fi

# update and convert robots.txt to block nasty AI companies
cd ai.robots.txt
python code/robots.py --update
python code/robots.py --convert
cp ./robots.txt ../output/robots.txt
cd ..

# set more strict file permissions on output directory
find $OUTPUT_DIR -type d -exec chmod 755 {} \;
find $OUTPUT_DIR -type f -exec chmod 644 {} \;

# push to server
## WARNING: with --delete anything beside website files in the server's /var/www/html will be deleted!
## NOTE: --checksum is expensive server-side, consider removing as site gets larger
su -c "rsync -av --checksum --delete $OUTPUT_DIR $SITE_USER@$SITE_URL:$SITE_PATH" $LOCAL_USER
